export const categories = [
  "إلكترونيات",
  "موبايلات",
  "كمبيوتر",
  "عطور",
  "ملابس",
  "أحذية",
  "أدوات منزلية",
  "سوبر ماركت",
  "مستحضرات تجميل",
  "قطع غيار السيارات",
];

export const products = [
  {
    id: "1",
    name: "عطر فاخر",
    category: "عطور",
    price: 12500,
    discount: 25,
    stock: 24,
    vendor: "متجر طيب الجنان للعطور",
    rating: 4.8,
    description: "عطر مناسب للهدايا والاستخدام اليومي برائحة ثابتة وجذابة.",
    image: "/products/perfume.svg",
  },
  {
    id: "2",
    name: "هاتف ذكي",
    category: "موبايلات",
    price: 145000,
    discount: 10,
    stock: 8,
    vendor: "متجر إلكترونيات الخرطوم",
    rating: 4.6,
    description: "هاتف عملي يناسب الاستخدام اليومي ويجمع بين الأداء والسعر المناسب.",
    image: "/products/phones.svg",
  },
  {
    id: "3",
    name: "حذاء رياضي",
    category: "أحذية",
    price: 27000,
    discount: 15,
    stock: 13,
    vendor: "متجر ملابس السودان",
    rating: 4.7,
    description: "حذاء مريح للحركة اليومية والخروج بأناقة بسيطة.",
    image: "/products/shoes.svg",
  },
  {
    id: "4",
    name: "سماعات لاسلكية",
    category: "إلكترونيات",
    price: 18500,
    discount: 18,
    stock: 18,
    vendor: "متجر إلكترونيات الخرطوم",
    rating: 4.4,
    description: "صوت واضح مع بطارية مناسبة للاستخدام طوال اليوم.",
    image: "/products/electronics.svg",
  },
  {
    id: "5",
    name: "ساعة ذكية",
    category: "إلكترونيات",
    price: 29500,
    discount: 12,
    stock: 11,
    vendor: "متجر إلكترونيات الخرطوم",
    rating: 4.5,
    description: "متابعة الصحة والتنبيهات والرسائل في تصميم عصري ومريح.",
    image: "/products/electronics.svg",
  },
  {
    id: "6",
    name: "مكواة بخار",
    category: "أدوات منزلية",
    price: 16500,
    discount: 8,
    stock: 14,
    vendor: "متجر البيت العصري",
    rating: 4.3,
    description: "مناسبة للكي السريع والعناية اليومية بالملابس.",
    image: "/products/home.svg",
  },
  {
    id: "7",
    name: "قهوة عربية",
    category: "سوبر ماركت",
    price: 8500,
    discount: 5,
    stock: 40,
    vendor: "متجر السوبر المميز",
    rating: 4.9,
    description: "طعم غني مناسب للضيافة والمناسبات.",
    image: "/products/grocery.svg",
  },
  {
    id: "8",
    name: "شنطة يد",
    category: "ملابس",
    price: 22000,
    discount: 20,
    stock: 9,
    vendor: "متجر ملابس السودان",
    rating: 4.5,
    description: "تصميم أنيق للاستخدام اليومي والمناسبات.",
    image: "/products/fashion.svg",
  },
  {
    id: "9",
    name: "كريم وجه",
    category: "مستحضرات تجميل",
    price: 9600,
    discount: 15,
    stock: 21,
    vendor: "متجر الجمال الطبيعي",
    rating: 4.7,
    description: "ترطيب وحماية مناسبة للبشرة مع ملمس خفيف.",
    image: "/products/beauty.svg",
  },
  {
    id: "10",
    name: "إطارات سيارة",
    category: "قطع غيار السيارات",
    price: 78000,
    discount: 7,
    stock: 6,
    vendor: "متجر قطع الغيار السريعة",
    rating: 4.2,
    description: "خيار عملي للسيارات الصغيرة والمتوسطة.",
    image: "/products/auto.svg",
  },
  {
    id: "11",
    name: "لاب توب عملي",
    category: "كمبيوتر",
    price: 320000,
    discount: 9,
    stock: 4,
    vendor: "متجر إلكترونيات الخرطوم",
    rating: 4.6,
    description: "مناسب للعمل والدراسة والمهام اليومية.",
    image: "/products/computer.svg",
  },
  {
    id: "12",
    name: "ماوس لاسلكي",
    category: "كمبيوتر",
    price: 6200,
    discount: 10,
    stock: 31,
    vendor: "متجر الكمبيوتر الذكي",
    rating: 4.4,
    description: "مريح وخفيف للعمل والدراسة.",
    image: "/products/computer.svg",
  },
  {
    id: "13",
    name: "شاحن سريع",
    category: "موبايلات",
    price: 5400,
    discount: 6,
    stock: 35,
    vendor: "متجر إلكترونيات الخرطوم",
    rating: 4.5,
    description: "شحن آمن وسريع للهواتف الحديثة.",
    image: "/products/phones.svg",
  },
  {
    id: "14",
    name: "طقم عناية شخصية",
    category: "مستحضرات تجميل",
    price: 14900,
    discount: 14,
    stock: 17,
    vendor: "متجر الجمال الطبيعي",
    rating: 4.8,
    description: "منتجات يومية للعناية والاهتمام الشخصي.",
    image: "/products/beauty.svg",
  },
  {
    id: "15",
    name: "بلوزة قطنية",
    category: "ملابس",
    price: 11800,
    discount: 11,
    stock: 26,
    vendor: "متجر ملابس السودان",
    rating: 4.3,
    description: "ملابس مريحة للمنزل والخروج اليومي.",
    image: "/products/fashion.svg",
  },
  {
    id: "16",
    name: "مقلاة غير لاصقة",
    category: "أدوات منزلية",
    price: 13200,
    discount: 9,
    stock: 19,
    vendor: "متجر البيت العصري",
    rating: 4.5,
    description: "مناسبة للأطباق اليومية مع تنظيف سهل.",
    image: "/products/home.svg",
  },
  {
    id: "17",
    name: "معطر جو",
    category: "سوبر ماركت",
    price: 4300,
    discount: 4,
    stock: 44,
    vendor: "متجر السوبر المميز",
    rating: 4.1,
    description: "رائحة لطيفة للمكاتب والمنازل.",
    image: "/products/grocery.svg",
  },
  {
    id: "18",
    name: "زيت محرك",
    category: "قطع غيار السيارات",
    price: 25500,
    discount: 7,
    stock: 10,
    vendor: "متجر قطع الغيار السريعة",
    rating: 4.4,
    description: "جودة مناسبة للصيانة الدورية.",
    image: "/products/auto.svg",
  },
  {
    id: "19",
    name: "سماعة ألعاب",
    category: "كمبيوتر",
    price: 22000,
    discount: 13,
    stock: 12,
    vendor: "متجر الكمبيوتر الذكي",
    rating: 4.6,
    description: "صوت محيطي لتجربة الألعاب والعمل.",
    image: "/products/computer.svg",
  },
  {
    id: "20",
    name: "لوشن جسم",
    category: "مستحضرات تجميل",
    price: 10500,
    discount: 9,
    stock: 16,
    vendor: "متجر الجمال الطبيعي",
    rating: 4.5,
    description: "ترطيب يومي بملمس خفيف.",
    image: "/products/beauty.svg",
  },
  {
    id: "21",
    name: "منظف مطبخ",
    category: "أدوات منزلية",
    price: 6900,
    discount: 7,
    stock: 28,
    vendor: "متجر البيت العصري",
    rating: 4.2,
    description: "تنظيف سريع مع رائحة منعشة.",
    image: "/products/home.svg",
  },
  {
    id: "22",
    name: "شيبس عائلي",
    category: "سوبر ماركت",
    price: 2400,
    discount: 3,
    stock: 60,
    vendor: "متجر السوبر المميز",
    rating: 4.0,
    description: "وجبة خفيفة مناسبة للتجمعات اليومية.",
    image: "/products/grocery.svg",
  },
];

export const orderStatuses = [
  "جديد",
  "قيد المعالجة",
  "تم الشحن",
  "وصل للمندوب",
  "تم التسليم",
  "ملغي",
];

export const adminStats = [
  { label: "عدد الطلبات", value: "128" },
  { label: "عدد العملاء", value: "74" },
  { label: "عدد البائعين", value: "12" },
  { label: "المبيعات اليومية", value: "258,000 جنيه سوداني" },
];
